//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot_Application2.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot_Application2.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Site Collection Logo.
        /// </summary>
        internal static string ChangeSiteCollectionLogo {
            get {
                return ResourceManager.GetString("ChangeSiteCollectionLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a subsite.
        /// </summary>
        internal static string CreateASubsite {
            get {
                return ResourceManager.GetString("CreateASubsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create new subsite.
        /// </summary>
        internal static string CreateNewSubsite {
            get {
                return ResourceManager.GetString("CreateNewSubsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Subsite.
        /// </summary>
        internal static string CreateSubsite {
            get {
                return ResourceManager.GetString("CreateSubsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do something else.
        /// </summary>
        internal static string DoSomethingElse {
            get {
                return ResourceManager.GetString("DoSomethingElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to new created subsite.
        /// </summary>
        internal static string GoToNewCreatedSubsite {
            get {
                return ResourceManager.GetString("GoToNewCreatedSubsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hi I&apos;m an Office 365 Bot. What can I do for you ?.
        /// </summary>
        internal static string HiImAnOffice365Bot {
            get {
                return ResourceManager.GetString("HiImAnOffice365Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Subsite Name.
        /// </summary>
        internal static string NewSubsiteName {
            get {
                return ResourceManager.GetString("NewSubsiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On which SPSite do you want to change the logo ? The click on the following links redirects you to display settings page..
        /// </summary>
        internal static string OnWhichSPSiteDoYouWantToChangeTheLogo {
            get {
                return ResourceManager.GetString("OnWhichSPSiteDoYouWantToChangeTheLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;s&gt;Please fill informations to create subsite.&lt;/s&gt;.
        /// </summary>
        internal static string PleaseFillInformationToCreateSubsite {
            get {
                return ResourceManager.GetString("PleaseFillInformationToCreateSubsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select SPSite.
        /// </summary>
        internal static string SelectSPSite {
            get {
                return ResourceManager.GetString("SelectSPSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show All Site Collections.
        /// </summary>
        internal static string ShowAllSiteCollections {
            get {
                return ResourceManager.GetString("ShowAllSiteCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Site Collection: .
        /// </summary>
        internal static string SiteCollection {
            get {
                return ResourceManager.GetString("SiteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à These are actions I can do. What would you like me to do?.
        /// </summary>
        internal static string TheseAreActionsICanDo {
            get {
                return ResourceManager.GetString("TheseAreActionsICanDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Web template to apply.
        /// </summary>
        internal static string WebTemplateToApply {
            get {
                return ResourceManager.GetString("WebTemplateToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What would you like me to do?.
        /// </summary>
        internal static string WhatWouldYouLikeMeToDo {
            get {
                return ResourceManager.GetString("WhatWouldYouLikeMeToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your subsite has been created..
        /// </summary>
        internal static string YourSubsiteHasBeenCreated {
            get {
                return ResourceManager.GetString("YourSubsiteHasBeenCreated", resourceCulture);
            }
        }
    }
}
